name: Node.js Playground
version: 0.3.8
slug: nodejs_playground
description: Open a browser terminal for running Node.js/npm apps inside Home Assistant OS.
url: https://github.com/ImBada/haos-nodejs-playground
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 7681
panel_icon: mdi:console
map:
  - addon_config:rw
  - share:rw
  - ssl:rw
  - media:rw
  - backup:rw
ports:
  3210/tcp: 3000
ports_description:
  3210/tcp: External web server port for your Node.js app
options:
  app_port: 3000
schema:
  app_port: port
